-- MySQL Script generated by MySQL Workbench
-- 10/20/19 15:05:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CourseWork2019
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CourseWork2019
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CourseWork2019` DEFAULT CHARACTER SET utf8 ;
USE `CourseWork2019` ;

-- -----------------------------------------------------
-- Table `CourseWork2019`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CourseWork2019`.`User` (
  `idUser` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Username` VARCHAR(45) NULL,
  `PassWord` VARCHAR(20) NULL,
  `Role` TINYINT GENERATED ALWAYS AS () VIRTUAL,
  `DateCreated` DATE NULL,
  `IsDeleted` TINYINT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CourseWork2019`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CourseWork2019`.`Customers` (
  `idCustomers` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `PhoneNumber` VARCHAR(10) NULL,
  `IsDeleted` TINYINT NULL,
  `DateCreated` DATE NULL,
  `CreatedBy` INT NOT NULL,
  PRIMARY KEY (`idCustomers`),
  INDEX `fk_Customers_User1_idx` (`CreatedBy` ASC),
  CONSTRAINT `fk_Customers_User1`
    FOREIGN KEY (`CreatedBy`)
    REFERENCES `CourseWork2019`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CourseWork2019`.`ProductType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CourseWork2019`.`ProductType` (
  `idProductType` INT NOT NULL,
  `Code` VARCHAR(10) NULL,
  `Name` VARCHAR(30) NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`idProductType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CourseWork2019`.`Amortization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CourseWork2019`.`Amortization` (
  `idAmortization` INT NOT NULL,
  `TimeElapsedInMonths` INT NOT NULL,
  `PriceReductionIn%` INT NOT NULL,
  PRIMARY KEY (`idAmortization`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CourseWork2019`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CourseWork2019`.`Product` (
  `idProduct` INT NOT NULL,
  `ProductType_idProductType` INT NOT NULL,
  `Amortization_idAmortization` INT NOT NULL,
  `IsDMA` TINYINT NULL,
  `IsDiscarded` TINYINT NULL,
  `Price` DOUBLE NULL,
  `CreadedBy` INT NOT NULL,
  `DateCreated` DATE NULL,
  `LoanedTo` INT NOT NULL,
  `IsDeleted` TINYINT NULL,
  PRIMARY KEY (`idProduct`),
  INDEX `fk_Product_ProductType1_idx` (`ProductType_idProductType` ASC),
  INDEX `fk_Product_Amortization1_idx` (`Amortization_idAmortization` ASC),
  INDEX `fk_Product_User1_idx` (`CreadedBy` ASC),
  INDEX `fk_Product_Customers1_idx` (`LoanedTo` ASC),
  CONSTRAINT `fk_Product_ProductType1`
    FOREIGN KEY (`ProductType_idProductType`)
    REFERENCES `CourseWork2019`.`ProductType` (`idProductType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Amortization1`
    FOREIGN KEY (`Amortization_idAmortization`)
    REFERENCES `CourseWork2019`.`Amortization` (`idAmortization`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_User1`
    FOREIGN KEY (`CreadedBy`)
    REFERENCES `CourseWork2019`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Customers1`
    FOREIGN KEY (`LoanedTo`)
    REFERENCES `CourseWork2019`.`Customers` (`idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
